# Generated by Django 3.1.2 on 2020-10-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practical_main', '0003_auto_20201009_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
