# Generated by Django 3.1.2 on 2020-10-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practical_main', '0005_auto_20201010_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='book_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
