# Generated by Django 3.1.2 on 2020-10-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practical_main', '0006_userprofile_book_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(default='', max_length=60)),
                ('isbn', models.CharField(default='', max_length=60)),
                ('author', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='book_name',
        ),
    ]
