# Generated by Django 3.1.2 on 2020-10-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practical_main', '0007_auto_20201011_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='author',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='books_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isbn',
            field=models.CharField(default='', max_length=60),
        ),
    ]
