# Generated by Django 3.1.2 on 2020-10-11 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practical_main', '0009_auto_20201011_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
